--Total Revenue
SELECT SUM(REVENUE) AS TOTAL_REVENUE
FROM CURATED.FACT_CDR;

--Total Calls
SELECT COUNT(*) AS TOTAL_CALLS
FROM CURATED.FACT_CDR;


-- Top Caller By Usage 
SELECT 
    CALLER,
    SUM(DURATION) AS TOTAL_DURATION
FROM CURATED.FACT_CDR
GROUP BY CALLER
ORDER BY TOTAL_DURATION DESC
LIMIT 5;

--International vs Local Calls
SELECT 
    IS_INTERNATIONAL,
    COUNT(*) AS CALL_COUNT
FROM CURATED.FACT_CDR
GROUP BY IS_INTERNATIONAL;

--High Usage Customer 
SELECT 
    CALLER,
    SUM(DURATION) AS TOTAL_DURATION
FROM CURATED.FACT_CDR
GROUP BY CALLER
HAVING SUM(DURATION) > 1000;