// BRONZE LAYER 
CREATE WAREHOUSE TELECOM_WH
WITH WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE TELECOM_DB;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA CURATED;
CREATE OR REPLACE SCHEMA ANALYTICS;

USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null','');

CREATE STAGE stage
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE TABLE telecom_db.raw.tower_master (
    TowerID STRING,
    Region  STRING,
    City    STRING
);


CREATE OR REPLACE TABLE telecom_db.raw.customer_master (
    PhoneNumber   STRING,
    CustomerName  STRING,
    PlanType      STRING
);

CREATE OR REPLACE TABLE telecom_db.raw.cdr_raw (
    CallID    STRING,
    Caller    STRING,
    Receiver  STRING,
    Duration  STRING,
    CallType  STRING,
    TowerID   STRING,
    Timestamp STRING
);

COPY INTO telecom_db.raw.tower_master
FROM @telecom_db.raw.stage/TOWER_MASTER_Telecom.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO telecom_db.raw.customer_master
FROM @telecom_db.raw.stage/CUSTOMER_MASTER_Telecom.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO telecom_db.raw.cdr_raw
FROM @telecom_db.raw.stage/CDR_RAW.csv
FILE_FORMAT = CSV_FORMAT;

SELECT * FROM TOWER_MASTER;

SELECT * FROM CUSTOMER_MASTER;

SELECT * FROM CDR_RAW;


REMOVE @stage/CDR_RAW_Telecom.csv;

// SILVER LAYER 
//TRANSFORMATION

USE SCHEMA STAGING;

CREATE OR REPLACE TABLE Staging.STG_CUSTOMERMASTER AS
SELECT DISTINCT
    
    REGEXP_REPLACE(PhoneNumber, '[^0-9]', '') AS PhoneNumber,
    INITCAP(CustomerName) AS CustomerName,
    CASE 
        WHEN UPPER(PlanType) LIKE '%PREPAID%' THEN 'PREPAID'
        WHEN UPPER(PlanType) LIKE '%POSTPAID%' THEN 'POSTPAID'
        WHEN UPPER(PlanType) LIKE '%VAT%' THEN 'VAT'
        WHEN UPPER(PlanType) LIKE '%DATA%' THEN 'VAT'
        ELSE 'UNKNOWN'
    END AS PLANTYPE,
    TRY_TO_NUMBER(REGEXP_SUBSTR(PlanType, '[0-9]+')) AS PlanPrice
FROM RAW.CUSTOMER_MASTER
WHERE LENGTH(REGEXP_REPLACE(PhoneNumber, '[^0-9]', '')) = 10;

SELECT * FROM Staging.STG_CUSTOMERMASTER;

//TOWER MASTER CLEAN 

CREATE OR REPLACE TABLE Staging.STG_TOWERMASTER AS
SELECT
    TRIM(TowerID) AS TowerID,

    INITCAP(TRIM(REGION)) AS Region,

    INITCAP(TRIM(CITY)) AS City,
FROM RAW.TOWER_MASTER
WHERE 
    TowerID IS NOT NULL;

SELECT * FROM Staging.STG_TOWERMASTER;

//cdr clean 

CREATE OR REPLACE TABLE STAGING.STG_CDR (
    CALLID INT,
    CALLER STRING,
    RECEIVER STRING,
    DURATION INT,
    CALL_TYPE STRING,
    TOWER_ID STRING,
    CALL_TIMESTAMP TIMESTAMP,
    REVENUE FLOAT,
    IS_INTERNATIONAL INT
);
INSERT INTO STAGING.STG_CDR
SELECT DISTINCT
    CALLID,
    CALLER,
    RECEIVER,
    NVL(DURATION, 0) AS DURATION,
    CALLTYPE,
    TOWERID,
    TRY_TO_TIMESTAMP(TIMESTAMP) AS CALL_TIMESTAMP,
    NVL(DURATION,0) * 0.02 AS REVENUE,
    CASE 
        WHEN CALLTYPE = 'INT' THEN 1 
        ELSE 0 
    END AS IS_INTERNATIONAL
FROM RAW.CDR_RAW
WHERE DURATION >= 0 OR DURATION IS NULL;

SELECT * FROM Staging.STG_CDR;

DROP STAGING.CDR_SILVER;

//CURATED
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CURATED.FACT_CDR (
    CDR_KEY INT AUTOINCREMENT,
    CALL_ID INT,
    CALLER STRING,
    RECEIVER STRING,
    DURATION INT,
    REVENUE FLOAT,
    IS_INTERNATIONAL INT,
    CALL_DATE DATE,
    TOWER_ID STRING
);

CREATE OR REPLACE TABLE CURATED.DIM_TOWER (
    TOWER_ID STRING PRIMARY KEY,
    REGION STRING,
    CITY STRING
);

INSERT INTO CURATED.DIM_TOWER
SELECT DISTINCT
    TOWERID,
    REGION,
    CITY
FROM STAGING.STG_TOWERMASTER;

SELECT * FROM CURATED.DIM_TOWER;

// MERGE 

MERGE INTO CURATED.FACT_CDR F
USING STAGING.STG_CDR S
ON F.CALL_ID = S.CALL_ID

WHEN MATCHED THEN UPDATE SET
    F.DURATION = S.DURATION,
    F.REVENUE = S.REVENUE

WHEN NOT MATCHED THEN INSERT (
    CALL_ID, CALLER, RECEIVER, DURATION,
    REVENUE, IS_INTERNATIONAL, CALL_DATE, TOWER_ID
)
VALUES (
    S.CALL_ID,
    S.CALLER,
    S.RECEIVER,
    S.DURATION,
    S.REVENUE,
    S.IS_INTERNATIONAL,
    DATE(S.CALL_TIMESTAMP),
    S.TOWER_ID
);


// ANALYTICS 

USE SCHEMA ANALYTICS ;

CREATE OR REPLACE TABLE ANALYTICS.HIGH_USAGE_ALERT (
    CALLER STRING,
    TOTAL_DURATION INT,
    ALERT_TIME TIMESTAMP
);

INSERT INTO ANALYTICS.HIGH_USAGE_ALERT
SELECT 
    CALLER,
    SUM(DURATION) AS TOTAL_DURATION,
    CURRENT_TIMESTAMP
FROM CURATED.FACT_CDR
GROUP BY CALLER
HAVING SUM(DURATION) > 1000;

SELECT * FROM HIGH_USAGE_ALERT;

INSERT INTO ANALYTICS.HIGH_USAGE_ALERT
SELECT 
    CALLER,
    SUM(DURATION) AS TOTAL_DURATION,
    CURRENT_TIMESTAMP
FROM CURATED.FACT_CDR
GROUP BY CALLER
HAVING SUM(DURATION) > 1000;

//AUTOMATION

CREATE OR REPLACE TASK ALERT_TASK
WAREHOUSE = TELECOM_WH
SCHEDULE = '1 MINUTE'
AS
INSERT INTO ANALYTICS.HIGH_USAGE_ALERT
SELECT 
    CALLER,
    SUM(DURATION),
    CURRENT_TIMESTAMP
FROM CURATED.FACT_CDR
GROUP BY CALLER
HAVING SUM(DURATION) > 1000;

ALTER TASK ALERT_TASK RESUME;

//VALIDATION CHECKS 


SELECT * FROM STAGING.STG_CDR
WHERE DURATION < 0;

SELECT * FROM STAGING.STG_CDR
WHERE CALLER IS NULL;

CREATE OR REPLACE NOTIFICATION INTEGRATION EMAIL_INT
TYPE = EMAIL
ENABLED = TRUE;

CREATE OR REPLACE PROCEDURE SEND_ALERT()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE CNT INT;
BEGIN

    SELECT COUNT(*) INTO :CNT
    FROM ANALYTICS.HIGH_USAGE_ALERT
    WHERE ALERT_TIME >= DATEADD(MINUTE, -5, CURRENT_TIMESTAMP);

    IF (CNT > 0) THEN
    
        CALL SYSTEM$SEND_EMAIL(
            'EMAIL_INT',
            'nawalmathur2@gmail.com',
            'High Usage Alert',
            'Some customers exceeded usage limit. Check Snowflake table.'
        );
        
    END IF;

    RETURN 'DONE';

END;
$$;

CREATE OR REPLACE TASK ALERT_EMAIL_TASK
WAREHOUSE = TELECOM_WH
SCHEDULE = '5 MINUTE'
AS
CALL SEND_ALERT();

ALTER TASK ALERT_EMAIL_TASK RESUME;

SELECT COUNT(*) 
FROM ANALYTICS.HIGH_USAGE_ALERT
WHERE ALERT_TIME >= DATEADD(MINUTE, -5, CURRENT_TIMESTAMP);

CALL SEND_ALERT();

